# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FluxEnvsubst < Formula
  desc "Environment variable substitution for Flux"
  homepage "https://jaconi.io/"
  version "1.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jaconi-io/flux-envsubst/releases/download/v1.0.8/flux-envsubst_1.0.8_darwin_arm64.tar.gz"
      sha256 "585b2cc7aa69262059670c3344fd92346044b7f69802eff63d90e0c012ab17a2"

      def install
        bin.install "flux-envsubst"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jaconi-io/flux-envsubst/releases/download/v1.0.8/flux-envsubst_1.0.8_darwin_amd64.tar.gz"
      sha256 "83d5634fa7fa0e2c4ce39b219593d72cac5f4b1b594e39518d082b6b364540b1"

      def install
        bin.install "flux-envsubst"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jaconi-io/flux-envsubst/releases/download/v1.0.8/flux-envsubst_1.0.8_linux_amd64.tar.gz"
      sha256 "16ccbb60fd76c716d539f38d88c461ebe82a8043f00edfb72723352347d585b2"

      def install
        bin.install "flux-envsubst"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jaconi-io/flux-envsubst/releases/download/v1.0.8/flux-envsubst_1.0.8_linux_arm64.tar.gz"
      sha256 "96f35f44d7f8c56212f77717bb9b7212b63a3a7d8958274fa03201fa156dccb6"

      def install
        bin.install "flux-envsubst"
      end
    end
  end
end
