# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FluxEnvsubst < Formula
  desc "Environment variable substitution for Flux"
  homepage "https://jaconi.io/"
  version "4.0.28"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jaconi-io/flux-envsubst/releases/download/v4.0.28/flux-envsubst_4.0.28_darwin_amd64.tar.gz"
      sha256 "1eb2a738b9666ce94c4aa9e12902d1f8631b3908f681968fd1857874fd383315"

      def install
        bin.install "flux-envsubst"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jaconi-io/flux-envsubst/releases/download/v4.0.28/flux-envsubst_4.0.28_darwin_arm64.tar.gz"
      sha256 "a139da393430a113dd2b33319d73d3be5162f0c495a4dc06f6dfb5efff0782d6"

      def install
        bin.install "flux-envsubst"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jaconi-io/flux-envsubst/releases/download/v4.0.28/flux-envsubst_4.0.28_linux_amd64.tar.gz"
      sha256 "bf97ac78da81db21a65451b34c7be6934fb6adf5b38ad6268c28db92364595e0"
      def install
        bin.install "flux-envsubst"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jaconi-io/flux-envsubst/releases/download/v4.0.28/flux-envsubst_4.0.28_linux_arm64.tar.gz"
      sha256 "23544c4ff236fc927f1731ef1890a2cc1c436858b402be23cf82a33f676959f4"
      def install
        bin.install "flux-envsubst"
      end
    end
  end
end
