# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FluxEnvsubst < Formula
  desc "Environment variable substitution for Flux"
  homepage "https://jaconi.io/"
  version "2.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jaconi-io/flux-envsubst/releases/download/v2.0.3/flux-envsubst_2.0.3_darwin_arm64.tar.gz"
      sha256 "ca1874620e6fc9aa2610384f3486ca89c418448c528f8d360feb4680eb4a4865"

      def install
        bin.install "flux-envsubst"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jaconi-io/flux-envsubst/releases/download/v2.0.3/flux-envsubst_2.0.3_darwin_amd64.tar.gz"
      sha256 "0270844fc14f0812e22c9c97f767ddcc91ffec9da5f74b5a917deabe961629f6"

      def install
        bin.install "flux-envsubst"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jaconi-io/flux-envsubst/releases/download/v2.0.3/flux-envsubst_2.0.3_linux_amd64.tar.gz"
      sha256 "1a26396c39c9b156a90c6890d42ffb753f7740dc0610b1e694bc0fc2adfd203d"

      def install
        bin.install "flux-envsubst"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jaconi-io/flux-envsubst/releases/download/v2.0.3/flux-envsubst_2.0.3_linux_arm64.tar.gz"
      sha256 "81f013ee0a74915dc52745b30c4ba2687001a8d526f2905b70dde65a1d329bb9"

      def install
        bin.install "flux-envsubst"
      end
    end
  end
end
